name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 875741101665.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t flask-cicd-app .

      - name: Tag Docker image
        run: docker tag flask-cicd-app:latest 875741101665.dkr.ecr.us-east-1.amazonaws.com/flask-cicd-app:latest

      - name: Push to ECR
        run: docker push 875741101665.dkr.ecr.us-east-1.amazonaws.com/flask-cicd-app:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster flask-cicd-cluster \
            --service flask-task-service-g5gfozlz \
            --force-new-deployment
